POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "joão",
    "email": "joão@",
    "password": "123456"
}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "meia",
    "price": 20,
    "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

###
GET http://localhost:3003/products?order=DESC


###
POST  http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "1662040589533",
    "product_id": "1662032163873",
    "quantity" : 1
}

###
GET http://localhost:3003/users/1661974877490/purchases

