POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "fulano",
    "email": "fulano@",
    "password": "123456"
}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "camiseta",
    "price": 50,
    "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

###
GET http://localhost:3003/products


###
POST  http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "1661974877490",
    "product_id": "1661973458994",
    "quantity" : 3
}

###
GET http://localhost:3003/users/1661974877490/purchases

